// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/lazywoo/mercury/pkg/wego"
	"github.com/lazywoo/mercury/sms/grpc"
	"github.com/lazywoo/mercury/sms/ioc"
)

// Injectors from wire.go:

func InitAPP() *wego.App {
	logger := ioc.InitFileLogger()
	service := ioc.InitService(logger)
	smsServiceServer := grpc.NewSmsServiceServer(service)
	server := ioc.InitGRPCxServer(smsServiceServer, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProviderSet = wire.NewSet(ioc.InitFileLogger)
