{
 "title": "Mercury 服务监控",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "http 响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "lazywoo_mercury_gin_http_response_time{job=\"mercury\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Groutine数量",
   "type": "timeseries",
   "description": "监控节点goroutine数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"mercury\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 活跃请求数",
   "type": "timeseries",
   "description": "http 活跃请求数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "lazywoo_mercury_gin_http_active_request{job=\"mercury\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}