// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/internal/api"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	captchaCache := cache.NewCaptchaCache(cmdable)
	captchaRepository := repository.NewCaptchaRepository(captchaCache)
	smsService := ioc.InitSMSService()
	captchaService := service.NewCaptchaService(captchaRepository, smsService)
	userHandler := api.NewUserHandler(userService, captchaService)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
