// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/lazywoo/mercury/captcha/grpc"
	"github.com/lazywoo/mercury/captcha/ioc"
	"github.com/lazywoo/mercury/captcha/repository"
	"github.com/lazywoo/mercury/captcha/repository/cache"
	"github.com/lazywoo/mercury/captcha/service"
	"github.com/lazywoo/mercury/pkg/wego"
)

// Injectors from wire.go:

func InitAPP() *wego.App {
	cmdable := ioc.InitRedis()
	captchaCache := cache.NewCaptchaRedisCache(cmdable)
	captchaRepository := repository.NewCachedCaptchaRepository(captchaCache)
	client := ioc.InitEtcdClient()
	smsServiceClient := ioc.InitSmsServiceClient(client)
	captchaService := service.NewCaptchaService(captchaRepository, smsServiceClient)
	captchaServiceServer := grpc.NewCaptchaServiceServer(captchaService)
	logger := ioc.InitLogger()
	server := ioc.InitGRPCxServer(captchaServiceServer, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProviderSet = wire.NewSet(ioc.InitLogger, ioc.InitRedis, ioc.InitEtcdClient, ioc.InitSmsServiceClient)

var svcProviderSet = wire.NewSet(grpc.NewCaptchaServiceServer, service.NewCaptchaService, repository.NewCachedCaptchaRepository, cache.NewCaptchaRedisCache)
