// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/tsukiyo/mercury/internal/comment/grpc"
	"github.com/tsukiyo/mercury/internal/comment/ioc"
	"github.com/tsukiyo/mercury/internal/comment/repository"
	"github.com/tsukiyo/mercury/internal/comment/repository/dao"
	"github.com/tsukiyo/mercury/internal/comment/service"
	"github.com/tsukiyo/mercury/pkg/app"
)

// Injectors from wire.go:

func InitAPP() *app.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	commentDAO := dao.NewCommentDAO(db)
	commentRepository := repository.NewCommentRepository(commentDAO, logger)
	commentService := service.NewCommentService(commentRepository)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	server := ioc.InitGRPCxServer(commentServiceServer, logger)
	appApp := &app.App{
		GRPCServer: server,
	}
	return appApp
}

// wire.go:

var thirdProviderSet = wire.NewSet(ioc.InitLogger, ioc.InitDB)

var serviceProviderSet = wire.NewSet(grpc.NewCommentServiceServer, service.NewCommentService, repository.NewCommentRepository, dao.NewCommentDAO)
