// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"

	"github.com/lazywoo/mercury/internal/oauth2/grpc"
	"github.com/lazywoo/mercury/internal/oauth2/ioc"
	"github.com/lazywoo/mercury/pkg/app"
)

// Injectors from wire.go:

func InitAPP() *app.App {
	logger := ioc.InitLogger()
	service := ioc.InitWechatService(logger)
	oAuth2ServiceServer := grpc.NewOAuth2ServiceServer(service)
	server := ioc.InitGRPCxServer(oAuth2ServiceServer, logger)
	appApp := &app.App{
		GRPCServer: server,
	}
	return appApp
}

// wire.go:

var thirdProviderSet = wire.NewSet(ioc.InitLogger)
